#!/bin/bash

NAME=tanga
DIR="`(cd $(dirname "$0") && pwd)`"

kubectl delete pod $NAME

cd /tmp
rm -f $NAME.yml
echo -ne "1\n$NAME\n\n" | $DIR/createPodwispro.sh

kubectl -n default apply -f $NAME.yaml

kubectl wait --for=condition=ready --timeout=60s pod $NAME
kubectl exec -it $NAME bash
