#!/bin/bash

# Copied and modified from http://xmodulo.com/measure-packets-per-second-throughput-high-speed-network-interface.html

INTERVAL="1"  # update interval in seconds

R1=`cat /sys/class/net/eth0/statistics/rx_bytes`
T1=`cat /sys/class/net/eth0/statistics/tx_bytes`
sleep $INTERVAL
R2=`cat /sys/class/net/eth0/statistics/rx_bytes`
T2=`cat /sys/class/net/eth0/statistics/tx_bytes`

TBPS=`expr $T2 - $T1`
RBPS=`expr $R2 - $R1`
echo "$RBPS $TBPS"
