#!/bin/env ruby
#### Change background in gnome3 && plasma

backgrounds = '/Secundario/rotsen/backgrounds'

random_dir = `find #{backgrounds}/ -type d | shuf -n1`.strip
random_pic = `find #{random_dir}/ | shuf -n1`.strip
old_pic = `gsettings get org.gnome.desktop.background picture-uri`.strip.gsub('file://', '')

# session = `pgrep -U $(whoami) /usr/bin/gnome-shell`.strip
session = `pidof /usr/bin/gnome-shell`.strip
#session = `pgrep -U $(whoami) plasmashell`.strip
dbus_address = `sudo grep -z DBUS_SESSION_BUS_ADDRESS /proc/#{session}/environ|cut -d= -f2-`.strip

puts "Changing #{old_pic} => #{random_pic}..."
`DBUS_SESSION_BUS_ADDRESS=#{dbus_address} gsettings set org.gnome.desktop.background picture-uri file://#{random_pic}`
# `gsettings set org.gnome.desktop.background picture-uri file://#{random_pic}`

if ARGV && ARGV[0]
  puts "Deleting #{old_pic}"
  `rm #{old_pic}`
end
